config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :category, only: [:index, :new, :create, :destroy] do
    resources :records, only: [:index, :new, :create]
  end
  root "category#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user: user
    can :manage, Entity, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_records, dependent: :destroy
  has_many :records, through: :category_records, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_record.rb
class CategoryRecord < ApplicationRecord
  belongs_to :category
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :category_records, dependent: :destroy
  has_many :category, through: :category_records

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 1, maximum: 150 }
  has_many :categories, dependent: :destroy
  has_many :records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if user_signed_in?
      @categories = current_user.categories
    else
      render 'splash'
    end
  end

  def new
    @category = Category.new
  end

  def create
    @user = current_user
    @category = @user.categories.new(category_params)
    if @category.save
      flash[:notice] = "#{@category.name} created successfully!"
      redirect_to category_index_path
    else
      flash[:alert] = @category.errors.full_messages.first
      render :new
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    if @category.destroy
      flash.now[:notice] = 'Category deleted successfully!'
      redirect_to category_index_path
    else
      flash.now[:alert] = 'Something went wrong while deleting the category!'
      render :index
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = current_user.categories.find(params[:category_id])
    @records = @category.records.order(created_at: :desc)
  end

  def new
    @category = current_user.categories.find(params[:category_id])
    @record = @category.records.new
  end

  def create
    @category = current_user.categories.find(params[:category_id])
    @record = current_user.records.new(record_params)
    if @record.save
      cateogry_record = @record.category_records.create(category_id: @category.id, record_id: @record_id)
      if cateogry_record.save
        flash.now[:notice] = "#{@record.name} created successfully!"
        redirect_to category_records_path(@category)
      else
        flash.now[:alert] = 'Something went wrong!'
        render :new
      end
    else
      flash.now[:alert] = @record.errors.full_messages.first
      render :new
    end
  end

  private

  def record_params
    params.require(:record).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/category/index.html.erb
<h1 class="text-center my-5">Categories</h1>
<% if @categories.count > 0 %>
  <div class="d-flex flex-column gap-3">
    <% @categories.each do |category| %>
      <div class="c_card card flex-row align-items-center p-2 gap-4">
        <%= image_tag category.icon %>
        <div class="card_info">
          <div>
            <%= link_to category.name, category_records_path(category) %>
            <%= button_to "Delete", category_path(category), method: :delete, class: "btn btn-danger" %>
          </div>
          <span class="text-muted"><%= l category.created_at.to_date, format: :long %></span>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h2 class="text-center">No categories found.</h2>
<% end %>
<div class="footer d-flex flex-column p-4">
  <%= link_to "Add a new Category", new_category_path, class: "btn back-green text-white" %>
</div>

app/views/category/new.html.erb
<section>
  <div class="d-flex align-items-center justify-content-around my-4">
    <%= link_to "Back", category_index_path, class: "btn btn-secondary" %>
    <h3>New Category</h3>
    <i></i>
  </div>
  <%= form_with model: @category, url: category_index_path, method: :post do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %><br />
      <%= f.text_field :name, class: "form-control" %>
    </div>
     <div class="mb-3">
      <%= f.label :icon, class: "form-label" %><br />
      <%= f.url_field :icon, class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "Create Category", class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/category/splash.html.erb
<section class="d-flex flex-column gap-5 mt-5">
  <h1 class="text-center">Rails Budget</h1>
  <div class="d-flex flex-column align-items-center gap-3">
    <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/records/index.html.erb
<div class="c_card card flex-row align-items-center p-2 gap-4">
  <%= image_tag @category.icon %>
  <div class="card_info">
    <h2><%= @category.name %></h2>
    <span class="text-muted">Total: $<%= @category.records.sum(&:amount) %></span>
  </div>
</div>
<div class="d-flex align-items-center justify-content-around mt-3 mb-5">
  <%= link_to "Back", category_index_path, class: "btn btn-secondary" %>
  <h3>Transactions</h3>
  <i></i>
</div>
  <% if @records.count > 0 %>
    <div class="d-flex flex-column gap-3">
      <% @records.each do |record| %>
        <div class="card p-2">
          <div class="d-flex justify-content-between">
            <span><%= record.name %></span>
            <div class="d-flex flex-column">
              <span>$<%= record.amount %></span>
              <span><%= l record.created_at.to_date, format: :long %></span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
  <h2 class="text-center">No Records found.</h2>
  <% end %>
<div class="footer d-flex flex-column p-4">
  <%= link_to "Create a new Record", new_category_record_path(@category), class: "btn back-green text-white" %>
</div>

app/views/records/new.html.erb
<section>
  <div class="d-flex align-items-center justify-content-around my-4">
    <%= link_to "Back", category_records_path(@category), class: "btn btn-secondary" %>
    <h3>New Transaction</h3>
    <i></i>
  </div>
  <%= form_with model: @record, url: category_records_path, method: :post do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %><br />
      <%= f.text_field :name, class: "form-control" %>
    </div>
     <div class="mb-3">
      <%= f.label :amount, class: "form-label" %><br />
      <%= f.number_field :amount, class: "form-control" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "Create Record", class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4 container-fluid w-50 d-flex flex-column align-items-center" role="alert">
    <%= flash[:notice] %>
  </div>
  <% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4 container-fluid w-50 d-flex flex-column align-items-center" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="back-primary navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Rails Budget</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse" id="navbarToggleExternalContent">
  <div class="back-primary p-4">
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class: "btn btn-outline-danger me-5" %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn" %>
      <%= link_to "Login", new_user_session_path, class: "btn" %>
    <% end %>
  </div>
  </div>
</nav>